# Generated by Django 3.1.5 on 2021-02-21 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('loginid', models.CharField(max_length=50, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 21, 12, 26, 12, 320242, tzinfo=utc), help_text='作成日')),
                ('created_user_id', models.IntegerField(blank=True, help_text='作成ユーザID', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日')),
                ('updated_user_id', models.IntegerField(blank=True, help_text='更新ユーザID', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='削除フラグ\u3000０：未削除\u3000１：削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='削除日', null=True)),
                ('deleted_user_id', models.IntegerField(blank=True, help_text='削除ユーザID', null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
