# Generated by Django 3.1.7 on 2021-02-23 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 3, 51, 0, 668196, tzinfo=utc), help_text='作成日'),
        ),
    ]
