# Generated by Django 3.1.7 on 2021-02-23 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20210223_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='記事のタイトル', max_length=100)),
                ('body', models.TextField()),
                ('push_title', models.CharField(help_text='プッシュ通知のタイトル', max_length=100)),
                ('push_body', models.CharField(help_text='プッシュ通知の本文', max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 2, 23, 3, 51, 46, 936454, tzinfo=utc), help_text='作成日')),
                ('created_user_id', models.IntegerField(blank=True, help_text='作成ユーザID', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日')),
                ('updated_user_id', models.IntegerField(blank=True, help_text='更新ユーザID', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='削除フラグ\u3000０：未削除\u3000１：削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='削除日', null=True)),
                ('deleted_user_id', models.IntegerField(blank=True, help_text='削除ユーザID', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 3, 51, 46, 936454, tzinfo=utc), help_text='作成日'),
        ),
    ]
