# Generated by Django 3.1.7 on 2021-02-25 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20210223_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 14, 54, 48, 541585, tzinfo=utc), help_text='作成日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 14, 54, 48, 541585, tzinfo=utc), help_text='作成日'),
        ),
    ]
