# Generated by Django 3.1.7 on 2021-02-27 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20210225_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 3, 16, 34, 782877, tzinfo=utc), help_text='作成日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 3, 16, 34, 782877, tzinfo=utc), help_text='作成日'),
        ),
    ]
