# Generated by Django 3.1.7 on 2021-03-03 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20210228_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 48, 50, 826255, tzinfo=utc), help_text='作成日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 48, 50, 826255, tzinfo=utc), help_text='作成日'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
