# Generated by Django 3.1.7 on 2021-03-03 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_auto_20210304_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 51, 0, 211267, tzinfo=utc), help_text='作成日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 51, 0, 211267, tzinfo=utc), help_text='作成日'),
        ),
        migrations.CreateModel(
            name='StampRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stamp', models.IntegerField()),
                ('created_at',
                 models.DateTimeField(default=datetime.datetime(2021, 3, 3, 16, 51, 0, 211267, tzinfo=utc),
                                      help_text='作成日')),
                ('created_user_id', models.IntegerField(blank=True, help_text='作成ユーザID', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日')),
                ('updated_user_id', models.IntegerField(blank=True, help_text='更新ユーザID', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='削除フラグ\u3000０：未削除\u3000１：削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='削除日', null=True)),
                ('deleted_user_id', models.IntegerField(blank=True, help_text='削除ユーザID', null=True)),
            ],
            options={
                'db_table': 'stamp_records',
            },
        ),
    ]
