# Generated by Django 3.1.7 on 2021-03-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_auto_20210304_0151'),
    ]

    sql = """
    create view stamp_total as 
        select
            ROW_NUMBER() OVER() AS id,
            users.id as user_id,
            sum(stamp_records.stamp) as total
        from users
        inner join users_groups on
            users.id = users_groups.user_id
            and users_groups.group_id = 2
        left join stamp_records on
            stamp_records.user_id = users.id
        group by users.id
    """

    reverse_sql = """
        DROP VIEW IF EXISTS stamp_total;
    """
    operations = [
        migrations.RunSQL(sql, reverse_sql),
    ]
